### ISSUE TITLE
ModuleNotFoundError: No module named 'tasks.rosvot.rosvot_utils'

### ISSUE THREAD

**Issue by fish0510** [RickyL-2000/ROSVOT#1] opened 2024-07-03 09:04 UTC
Hello,

I encountered an issue while trying to run _inference/rosvot.py_. Specifically, I am getting the following error:
`ModuleNotFoundError: No module named 'tasks.rosvot.rosvot_utils'`
I think there are some missing codes in the repo.

Thank you for your assistance.

**Comment by RickyL-2000** [comment] 2024-07-03 09:08
Thanks. I think the problem is fixed now.

**Closed as completed** 2024-07-03 09:19 UTC
